# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 02:16
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('setting_street', '0001_initial'),
        ('setting_globall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressFacilityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_home', models.IntegerField(blank=True, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0434\u043e\u043c\u0430')),
                ('literal', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0411\u0443\u043a\u0432\u0435\u043d\u043d\u044b\u0439 \u0438\u043d\u0434\u0435\u043a\u0441')),
                ('number_apartment', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u043a\u0432\u0430\u0440\u0442\u0438\u0440\u044b')),
                ('price_bay', models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430(\u0432\u044b\u043a\u0443\u043f)')),
                ('price_month', models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430(\u043c\u0435\u0441\u044f\u0446)')),
                ('price_day', models.IntegerField(default=0, verbose_name='\u0426\u0435\u043d\u0430(\u043f\u043e\u0441\u0443\u0442\u043e\u0447\u043d\u043e)')),
                ('landmark', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u041e\u0440\u0438\u0435\u043d\u0442\u0438\u0440')),
                ('number_of_floors', models.IntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436\u043d\u043e\u0441\u0442\u044c \u043e\u0442')),
                ('floors_up', models.IntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436\u043d\u043e\u0441\u0442\u044c \u0434\u043e')),
                ('first_floor', models.BooleanField(verbose_name='\u041f\u0435\u0440\u0432\u044b\u0439')),
                ('last_floor', models.BooleanField(verbose_name='\u041f\u043e\u0441\u043b\u0435\u0434\u043d\u0438\u0439')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='\u042d\u0442\u0430\u0436')),
                ('area_badroom', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0421\u043f\u0430\u043b\u044c\u043d\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('area_kitchen', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u0443\u0445\u043d\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('area_living_room', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0413\u043e\u0441\u0442\u0438\u043d\u043d\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('area_extra_room', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u0414\u043e\u043f.\u043a\u043e\u043c\u043d\u0430\u0442\u0430 \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('total_area', models.IntegerField(blank=True, null=True, verbose_name='\u041e\u0431\u0449\u0430\u044f \u043f\u043b\u043e\u0449\u0430\u0434\u044c')),
                ('payments', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041f\u043b\u0430\u0442\u0435\u0436\u0438')),
                ('rooms', models.IntegerField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442')),
                ('comment', models.TextField(null=True, verbose_name='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('commission', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u041a\u043e\u043c\u0438\u0441\u0441\u0438\u044f')),
                ('images_count', models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0444\u043e\u0442\u043e')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('youtube', models.TextField(blank=True, null=True, verbose_name='YouTube')),
                ('panorama', models.TextField(blank=True, null=True, verbose_name='\u041f\u0430\u043d\u043e\u0440\u0430\u043c\u0430')),
                ('lot', models.IntegerField(blank=True, null=True, verbose_name='\u0423\u0447\u0430\u0441\u0442\u043e\u043a')),
                ('sleeps', models.IntegerField(blank=True, null=True, verbose_name='\u0421\u043f\u0430\u043b\u044c\u043d\u044b\u0445 \u043c\u0435\u0441\u0442')),
                ('date_of_renovation', models.DateTimeField(auto_now=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('public', models.BooleanField(default=0, verbose_name='\u041f\u0443\u0431\u043b\u0438\u043a\u0443\u0435\u0442\u044c\u0441\u044f')),
            ],
            options={
                'verbose_name': '\u0410\u0434\u0440\u0435\u0441\u0441 \u043e\u0431\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u0410\u0434\u0440\u0435\u0441\u0441\u0430 \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='DatabasePhoneOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id_owner', models.CharField(blank=True, max_length=16, null=True, verbose_name='ID')),
                ('db_phone_owner', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u0438 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430',
                'verbose_name_plural': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u0438 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0435\u0432',
            },
        ),
        migrations.CreateModel(
            name='ImagesFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'img_obj/%Y/%m/%d/%H/%M/', verbose_name='\u0424\u043e\u0442\u043e')),
                ('cover', models.BooleanField(default=0, verbose_name='\u041e\u0431\u043b\u043e\u0436\u043a\u0430')),
            ],
            options={
                'verbose_name': '\u0424\u043e\u0442\u043e \u043e\u0431\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u0424\u043e\u0442\u043e \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='PhoneOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u0438 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430',
                'verbose_name_plural': '\u0422\u0435\u043b\u0435\u0444\u043e\u043d\u0438 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0435\u0432',
            },
        ),
        migrations.CreateModel(
            name='TypeActuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_actuality', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0430\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u0438',
            },
        ),
        migrations.CreateModel(
            name='TypeBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_building', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0440\u043e\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0441\u0442\u0440\u043e\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='TypeCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_condition', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u044f',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='TypeContactOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contact_owner', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u043e\u0432 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430',
            },
        ),
        migrations.CreateModel(
            name='TypeEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_equipment', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0442\u0435\u0445\u043d\u0438\u043a\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0442\u0435\u0445\u043d\u0438\u043a\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0442\u0435\u0445\u043d\u0438\u043a',
            },
        ),
        migrations.CreateModel(
            name='TypeFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_facility', models.CharField(max_length=50, unique=True, verbose_name='\u0422\u0438\u043f \u043e\u0431\u0435\u043a\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043e\u0431\u0435\u043a\u0442\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043e\u0431\u044a\u0435\u043a\u0442\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='TypeFurniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_furniture', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u041c\u0435\u0431\u0435\u043b\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u041c\u0435\u0431\u0435\u043b\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u041c\u0435\u0431\u0435\u043b\u0438',
            },
        ),
        migrations.CreateModel(
            name='TypeHeating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_heating', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u044f',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='TypeLavatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_lavatory', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0421\u0430\u043d\u0443\u0437\u043b\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0421\u0430\u043d\u0443\u0437\u043b\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0421\u0430\u043d\u0443\u0437\u043b\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='TypeNumberOfPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_number_of_persons', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a',
            },
        ),
        migrations.CreateModel(
            name='TypeOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operations', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0439',
            },
        ),
        migrations.CreateModel(
            name='TypePrepayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_prepayment', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u041f\u0440\u0435\u0434\u043e\u043f\u043b\u0430\u0442\u044b')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u041f\u0440\u0435\u0434\u043e\u043f\u043b\u0430\u0442\u044b',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u041f\u0440\u0435\u0434\u043e\u043f\u043b\u0430\u0442',
            },
        ),
        migrations.CreateModel(
            name='TypeRepairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_repairs', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0440\u0435\u043c\u043e\u043d\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0440\u0435\u043c\u043e\u043d\u0442\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0440\u0435\u043c\u043e\u043d\u0442\u0430',
            },
        ),
        migrations.CreateModel(
            name='TypeRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rooms', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u041a\u043e\u043c\u043d\u0430\u0442\u044b')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u041a\u043e\u043c\u043d\u0430\u0442\u044b',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u041a\u043e\u043c\u043d\u0430\u0442',
            },
        ),
        migrations.CreateModel(
            name='TypeThePresenceOfHotWater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_the_presence_of_hot_water', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0433\u043e\u0440\u044f\u0447\u0435\u0439 \u0432\u043e\u0434\u044b')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0433\u043e\u0440\u044f\u0447\u0435\u0439 \u0432\u043e\u0434\u044b',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u041d\u0430\u043b\u0438\u0447\u0438\u0435 \u0433\u043e\u0440\u044f\u0447\u0435\u0439 \u0432\u043e\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='TypeWhereToStay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_where_to_stay', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u0413\u0434\u0435 \u0441\u043f\u0430\u0442\u044c?')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0413\u0434\u0435 \u0441\u043f\u0430\u0442\u044c?',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0413\u0434\u0435 \u0441\u043f\u0430\u0442\u044c?',
            },
        ),
        migrations.CreateModel(
            name='TypeWindows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_windows', models.CharField(max_length=50, null=True, unique=True, verbose_name='\u0422\u0438\u043f \u041e\u043a\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u041e\u043a\u043d\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u041e\u043a\u043e\u043d',
            },
        ),
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactOwner',
            fields=[
                ('addressfacilitydata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='facility.AddressFacilityData')),
                ('agency', models.CharField(blank=True, max_length=250, verbose_name='\u0410\u0433\u0435\u043d\u0441\u0442\u0432\u043e')),
                ('name_owner', models.CharField(blank=True, max_length=250, verbose_name='\u0418\u043c\u044f \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430')),
                ('name_owner_ext', models.CharField(blank=True, max_length=250, verbose_name='\u0418\u043c\u044f \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430 \u0434\u043e\u043f.')),
                ('name_owner_ext2', models.CharField(blank=True, max_length=250, verbose_name='\u0418\u043c\u044f \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430 \u0434\u043e\u043f.2')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='\u041f\u0435\u0440\u0435\u0441\u043c\u043e\u0442\u0440 \u0414\u0430\u0442\u0430')),
                ('review_time', models.TimeField(auto_now_add=True, null=True, verbose_name='\u041f\u0435\u0440\u0435\u0441\u043c\u043e\u0442\u0440 \u0412\u0440\u0435\u043c\u044f')),
                ('call_date', models.DateField(blank=True, null=True, verbose_name='\u0417\u0432\u043e\u043d\u043e\u043a \u0414\u0430\u0442\u0430')),
                ('call_time', models.TimeField(auto_now_add=True, null=True, verbose_name='\u0417\u0432\u043e\u043d\u043e\u043a \u0412\u0440\u0435\u043c\u044f')),
                ('email_owner', models.EmailField(blank=True, max_length=150, null=True, verbose_name='E-mail \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430')),
                ('vip_owner', models.BooleanField(verbose_name=b'Vip')),
                ('phone_owner', models.CharField(max_length=16, null=True, verbose_name='\u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('phone_owner_plus', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b. \u0422\u0435\u043b\u0435\u0444\u043e\u043d')),
                ('phone_owner_plus2', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u0414\u043e\u043f\u043e\u043b. \u0422\u0435\u043b\u0435\u0444\u043e\u043d-2')),
                ('trash', models.BooleanField(default=False, verbose_name='\u041a\u043e\u0440\u0437\u0438\u043d\u0430')),
                ('time_trash', models.DateTimeField(blank=True, null=True, verbose_name='\u0412\u0440\u0435\u043c\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f')),
                ('name_user_trash', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u041a\u0442\u043e \u0443\u0434\u0430\u043b\u0438\u043b')),
                ('contact_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeContactOwner', verbose_name='\u0422\u0438\u043f \u043a\u043e\u043d\u0442\u0430\u043a\u0442\u0430 \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0430',
                'verbose_name_plural': '\u041a\u043e\u043d\u0442\u0430\u043a\u0442\u044b \u0432\u043b\u0430\u0434\u0435\u043b\u044c\u0446\u0435\u0432',
            },
            bases=('facility.addressfacilitydata',),
        ),
        migrations.AddField(
            model_name='imagesfacility',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='facility.AddressFacilityData', verbose_name='\u0410\u043b\u044c\u0431\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='actuality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeActuality', verbose_name='\u0410\u043a\u0442\u0443\u0430\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeCondition', verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='currency',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.PROTECT, to='setting_globall.NationalCarrency', verbose_name='\u0412\u0430\u043b\u044e\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='district_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setting_street.District', to_field=b'district', verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='facility.TypeEquipment', verbose_name='\u0422\u0435\u0445\u043d\u0438\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='furniture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeFurniture', verbose_name='\u041c\u0435\u0431\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='heating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeHeating', verbose_name='\u041e\u0442\u043e\u043f\u043b\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='lavatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeLavatory', verbose_name='\u0421\u0430\u043d\u0443\u0437\u0435\u043b'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='list_operations',
            field=models.ManyToManyField(to='facility.TypeOperations', verbose_name='\u0422\u0438\u043f \u043e\u043f\u0435\u0440\u0430\u0446\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='loyality',
            field=models.ManyToManyField(blank=True, related_name='loyal', to='facility.UserFullName', verbose_name='\u041b\u043e\u044f\u043b\u044c\u043d\u043e\u0441\u0442\u044c'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='number_of_persons',
            field=models.ManyToManyField(blank=True, to='facility.TypeNumberOfPerson', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='prepayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypePrepayment', verbose_name='\u041f\u0440\u0435\u0434\u043e\u043f\u043b\u0430\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='repairs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeRepairs', to_field=b'type_repairs', verbose_name='\u0420\u0435\u043c\u043e\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='rieltor',
            field=models.ManyToManyField(blank=True, to='facility.UserFullName', verbose_name='\u0420\u0438\u0435\u043b\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeRooms', verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='street_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setting_street.Street', to_field=b'full_street', verbose_name='\u0423\u043b\u0438\u0446\u0430'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='subway_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setting_street.Subway', to_field=b'subway', verbose_name='\u041c\u0435\u0442\u0440\u043e'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='the_presence_of_hot_water',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeThePresenceOfHotWater', verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='type_building_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeBuilding', to_field=b'type_building', verbose_name='\u0421\u0442\u0440\u043e\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='type_facilit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeFacility', to_field=b'type_facility', verbose_name='\u0422\u0438\u043f \u043e\u0431\u0435\u043a\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='where_to_stay',
            field=models.ManyToManyField(blank=True, to='facility.TypeWhereToStay', verbose_name='\u0413\u0434\u0435 \u0441\u043f\u0430\u0442\u044c ?'),
        ),
        migrations.AddField(
            model_name='addressfacilitydata',
            name='windows',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeWindows', verbose_name='\u041e\u043a\u043d\u0430'),
        ),
        migrations.AddField(
            model_name='phoneowner',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.ContactOwner'),
        ),
    ]
