# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0412\u043e\u0434\u044f\u043d\u043e\u0439 \u0437\u043d\u0430\u043a')),
                ('watermark_img', models.ImageField(upload_to=b'watermark', verbose_name='\u0412\u043e\u0434\u044f\u043d\u043e\u0439 \u0437\u043d\u0430\u043a')),
                ('on_off', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '\u0412\u043e\u0434\u044f\u043d\u043e\u0439 \u0437\u043d\u0430\u043a',
                'verbose_name_plural': '\u0412\u043e\u0434\u044f\u043d\u043e\u0439 \u0437\u043d\u0430\u043a',
            },
        ),
    ]
