# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arendator', '0001_initial'),
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arendator',
            name='number_of_persons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facility.TypeNumberOfPerson', verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0447\u0435\u043b\u043e\u0432\u0435\u043a'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='repairs',
            field=models.ManyToManyField(blank=True, to='facility.TypeRepairs', verbose_name='\u0420\u0435\u043c\u043e\u043d\u0442'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='rieltor',
            field=models.ManyToManyField(blank=True, related_name='arendator_rielt', to='arendator.UserFullName', verbose_name='\u0420\u0438\u0435\u043b\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='room',
            field=models.ManyToManyField(blank=True, to='facility.TypeRooms', verbose_name='\u041a\u043e\u043c\u043d\u0430\u0442\u044b'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='type_building_data',
            field=models.ManyToManyField(blank=True, to='facility.TypeFacility', verbose_name='\u0422\u0438\u043f \u043e\u0431\u044a\u0435\u043a\u0442\u0430'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='type_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t_client', to='arendator.TypeClient'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='type_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arendator.TypeStage', verbose_name='\u042d\u0442\u0430\u043f'),
        ),
        migrations.AddField(
            model_name='arendator',
            name='type_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='arendator.TypeState', verbose_name='\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435'),
        ),
        migrations.AlterUniqueTogether(
            name='arendator',
            unique_together=set([('name', 'phone_first')]),
        ),
    ]
