# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.TextField(verbose_name='Tекст Нотатки'),
        ),
    ]
