# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20160618_0138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Нотатка', 'verbose_name_plural': 'Нотатки'},
        ),
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
    ]
