# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigParserOLXSolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CITY', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u0413\u043e\u0440\u043e\u0434')),
                ('SITE_URL', models.CharField(blank=True, max_length=250, null=True, verbose_name='SITE_URL')),
                ('AJAX_PHONE', models.CharField(blank=True, max_length=250, null=True, verbose_name='AJAX_PHONE')),
                ('SELECTOR_GETLINK_CATEGORIES', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_GETLINK_CATEGORIES')),
                ('SELECTOR_GETTEXT_CATEGORIES', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_GETTEXT_CATEGORIES')),
                ('SELECTOR_GETLINK_ARTICLES', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_GETLINK_ARTICLES')),
                ('SELECTOR_SITY', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_SITY')),
                ('SELECTOR_TITLE', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_TITLE')),
                ('SELECTOR_DATE', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_DATE')),
                ('SELECTOR_PRICE', models.CharField(blank=True, max_length=250, null=True, verbose_name='SELECTOR_PRICE')),
            ],
            options={
                'verbose_name': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0430 \u043f\u0430\u0440\u0441\u0435\u0440\u0430',
                'verbose_name_plural': '\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043f\u0430\u0440\u0441\u0435\u0440\u0430',
            },
        ),
    ]
