
source ../data/bin/activate

python manage.py makemigrations arendator
python manage.py makemigrations backupbd_crm
python manage.py makemigrations buyer
python manage.py makemigrations extuser
python manage.py makemigrations facility
python manage.py makemigrations homes
python manage.py makemigrations learning
python manage.py makemigrations makler
python manage.py makemigrations meeting
python manage.py makemigrations notes
python manage.py makemigrations parsings
python manage.py makemigrations posting
python manage.py makemigrations searching
python manage.py makemigrations send_messege_user
python manage.py makemigrations sender_email
python manage.py makemigrations setting_globall
python manage.py makemigrations setting_street
python manage.py makemigrations setting_superadmin
python manage.py makemigrations setting_mail_delivery
python manage.py makemigrations single_arendator
python manage.py makemigrations single_buyer
python manage.py makemigrations single_object
python manage.py makemigrations tasking
python manage.py makemigrations trash_object
python manage.py makemigrations watermark
python manage.py makemigrations who_online
python manage.py makemigrations static

python manage.py migrate arendator
python manage.py migrate backupbd_crm
python manage.py migrate buyer
python manage.py migrate extuser
python manage.py migrate facility
python manage.py migrate homes
python manage.py migrate learning
python manage.py migrate makler
python manage.py migrate meeting
python manage.py migrate notes
python manage.py migrate parsings
python manage.py migrate posting
python manage.py migrate searching
python manage.py migrate send_messege_user
python manage.py migrate sender_email
python manage.py migrate setting_globall
python manage.py migrate setting_street
python manage.py migrate setting_superadmin
python manage.py migrate setting_mail_delivery
python manage.py migrate single_arendator
python manage.py migrate single_buyer
python manage.py migrate single_object
python manage.py migrate tasking
python manage.py migrate trash_object
python manage.py migrate watermark
python manage.py migrate who_online
python manage.py migrate static