# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 02:16
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('arendator', '0002_auto_20170516_0216'),
        ('facility', '0001_initial'),
        ('buyer', '0002_auto_20170516_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meet_date', models.DateTimeField(verbose_name='\u0414\u0430\u0442\u0430')),
                ('meet_comment', models.TextField(blank=True, null=True, verbose_name='\u041a\u043e\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439')),
                ('meet_trash', models.BooleanField(default=False, verbose_name=b'\xd0\x92 \xd0\xba\xd0\xbe\xd1\x80\xd0\xb7\xd0\xb8\xd0\xbd\xd1\x83')),
                ('meet_archiv', models.BooleanField(default=False, verbose_name=b'\xd0\x92 \xd0\xb0\xd1\x80\xd1\x85\xd0\xb8\xd0\xb2')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ['meet_date'],
                'verbose_name': '\u0412\u0441\u0442\u0440\u0435\u0447\u0438',
                'verbose_name_plural': '\u0412\u0441\u0442\u0440\u0435\u0447\u0438',
            },
        ),
        migrations.CreateModel(
            name='TypeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0422\u0438\u043f \u0441\u0442\u0430\u0442\u0443\u0441\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0441\u0442\u0430\u0442\u0443\u0441\u0430',
                'verbose_name_plural': '\u0422\u0438\u043f\u0438 \u0441\u0442\u0430\u0442\u0443\u0441\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='meet_access', to='meeting.UserFullName', verbose_name='\u0414\u043e\u0441\u0442\u0443\u043f'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_arendator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arendator.Arendator', verbose_name='ID(A) \u0410\u0440\u0435\u043d\u0434\u0430\u0442\u043e\u0440'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.Buyer', verbose_name='ID(P) \u041f\u043e\u043a\u0443\u043f\u0430\u0442\u0435\u043b\u044c'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facility.ContactOwner', verbose_name='ID(O) \u041e\u0431\u044a\u0435\u043a\u0442'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meet_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting.TypeStatus', verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='rieltor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='meeting.UserFullName', verbose_name='\u0420\u0438\u0435\u043b\u0442\u043e\u0440'),
        ),
    ]
